// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqpRdu-Myl4K3J2YmDx1A5gKn980RytE',
    appId: '1:183829261962:web:c1850aec3665f6fef18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    authDomain: 'drinkingapp-84ac5.firebaseapp.com',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
    measurementId: 'G-5ZTBCG8VPL',
  );
}
